### PR TITLE
Edited README with header

### PR DESCRIPTION
**Pull request by mariosworksearch**

### CODE REVIEW

**Comment by mariosworksearch** [comment]
Add your .vimrc

**Comment by useraddmario** [comment]
Add your .vimrc loser machine.

**Comment by useraddmario** [comment]
looks good, but squash those changes loser

**Comment by useraddmario** [comment]
Add a header for the .vimrc contents

**Comment by mariosworksearch** [comment]
Change made

**Comment by useraddmario** [comment]
Closes #1

**Pull request merged**
